---
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
deploy:
  api_key:
    secure: NM+7A5nCXjPrgyVim9coaC9ibzH+a4TAzMAs/JCaJmK9N9CkY5pq3TG4NOhbdSHa4Roku0YLo+sORTRZ7uT+8u5ey9A4cQTb2CNwPMhI68hN4JZiUJG42+1qK9dOxMe0piK5/K13papVLxJu+wSdHKfXgnXnkkQWVp0sZ9QfDd57SDVZY7x6r/4V8fT60hDn64Y7HMZNOKp84zj9DxnfLQZ4P/ap5F7e0vztXE7Dpt7f97RdS1ksFVR3C6uW2It1M9EkmxBAMmValMKv+8UjoVf3F25WxCkXWmbGzVZT2SYau3Mx0IDutX/9XketOS3Ca6zxl20fVcnmAvkCNT1K1zMnTK9Gku5Zr8yp0sFUQSUoZtW9c8dFkqZV5YgMKaPVwsx5KjtjvGsQmhIfwpYa8RPToWeZ4uWWYFowkPrkqQX3HGs+SgYFpQc++rYf1tITY5OIjuPPHl9sFb8ROudUP0pwZyg+sFEt0Hxdg+YNF1eSoow7rBc8KvuF6NwpIhCaQWtZHRp1G85MFwcmEDPi93x+Hfz08OLir5gvFJs4h4bJsQ0O26lWkXA0CWxxbG1CixEEI31nyVzMQokjJl3cvcZ4HaGRAu55AHHWkOiadUYXdlrKjMJ0icUVPZDngctRdBdyBnlesqx7G0xI7dq8SADnsK/UxKSGj/HF9oStxPM=
  gem: yaml_normalizer
  provider: rubygems
  true:
    repo: Sage/yaml_normalizer
    tags: true
env:
  global:
    secure: WqpYvyO2qbuhENdMu4ZWQeCp3kzpkQaEtmyOpfUlQxmFECeMxh+GJcX//+5Zn+4AjiTeVoraJCBQRz0QfgNpo9LK+vx/RGMphAXfMImDgvf6tR8sG/nbuYaUNuoj4mNssoahuwdvxUED0dMzFY8rKp1kCOHZql3p57Qof6E3FMbsDorEbfooXXIhLQR9log2RjF17AVpEZaJHZcC9+to1iEzRDn5e3/IzfcrQZ9FUgLatNXoliL6qQZh0veURIL985U2VhISmeEZwYX9e9dBF82LKx+xyq4wXtCp2aAs88swsM2s7j6EASDE7HGorcURvj7ZWS6CR7iQb69aQVTjUoXxNw1BxZevCV8iy1FHxjHCjMDZPmO2Y9xolFuqxaTU6E7Uu+VQRqHmLAsc6he16QVrUYyv34aFzxkDO+Hb0qK5I8hYMtli7pOibkdudqnur4HqvSLNDBDvv638fhmCXnnPLfH6yDx2KXIbpErIPCsZyHHxZTg7kGsgu2vPFkSmF+YKvKuZEDLqcI/Ttdqop1JOgaiOULqCIUJl5nKrSoQXMVtHuzxGOcxWK/iR/jgR3/n3SNJsddiyOpCq1Uwwf6xhwhKphFm49NG8TBPqLpoqkwJ3DJ6DB/7oHLmW6mQgSGDwODjeXsx5RKRTiSBtw/lftS+1jCnhekNtzku6whU=
language: ruby
rvm:
- 2.4
sudo: false
